### PR TITLE
fix broken progress bar counter

### PR DESCRIPTION
**Pull request by dadaphl**

### CODE REVIEW

**Review by nikita-fuchs — COMMENTED** [review]
LGTM

**Review by lucafavatella — APPROVED** [review]
Where does end come from?

Where do files for line `if (fs.existsSync("./.cfg") && fs.existsSync("./genesis.json"))` come from?

I did not test this though the changes seem ok, and the errors logged.

**Review by lucafavatella — APPROVED** [review]

**Review by nikita-fuchs — APPROVED** [review]
lgtm again

**Comment by dadaphl** [comment]
@lucafavatella Thank you for your review!

Your comment refers to changes that have nothing to do with this PR, please raise a separate issue.

**Pull request merged**
